### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by orionzhou** [orbitz/paramugsy#1]
Hi, 

I have used the serial version of this tool (mugsy) and found it a fantastic - faster and much more accurate than other aligners! Now since I have more genomes to align I think it'd great to install the parallel version. I'm a complete outsider of ocaml - I struggled to have all the dependencies installed but got stuck with this error. Any guidance or comments would be greatly appreciated! Thanks so much in advance!

During compilation of the code I ended up with this error:

```
make[3]: Entering directory `/panfs/roc/groups/5/youngn/zhoup/git/para-mugsy/lib/profiles'
ocamlfind ocamlopt -package core_extended,str,seq,ocaml_bio,threads -c -thread -I +camlp4 m_profile.ml
File "m_profile.ml", line 5, characters 38-49:
Error: Signature mismatch:
       ...
       Values do not match:
         val map : 'a t -> f:('a -> 'b) -> 'b t
       is not included in
         val map :
           [ `Custom of 'a t -> f:('a -> 'b) -> 'b t | `Define_using_bind ]
make[3]: *** [m_profile.cmx] Error 2
make[3]: Leaving directory `/panfs/roc/groups/5/youngn/zhoup/git/para-mugsy/lib/profiles'
```

Line 5 in file "m_profile.ml" is:
`"module Option_monad = Core.Monad.Make(Core.Option)"`

**Comment by orbitz** [comment]
Hey, this is the result of a mismatch in the Core version.

If you don't mind waiting a few days, I'll fix this + post a proper opam package to make installing (hopefully) easier.

**Comment by orionzhou** [comment]
Sounds great - thanks!

**Comment by orionzhou** [comment]
Hi, I'm wondering since this is an issue with later Core version, is it possible to simply switch back to an older Core version and re-compile the code? If so, which version were you using when writing the code - I know it's long time ago but would really appreciate your input.

I know it seems a little impatient for me to go for this dirty fix - I'm just trying to get it work and output something so I can start working on. I'd be more than glad to wait for your official fix while working on making sense of the output and connecting with the downstream analysis.

Thanks again for your help,

**Comment by orbitz** [comment]
Yes, although I'm afraid I have no idea which version it would be.

Also, what version of Linux are you running?  If Ubuntu this prebuilt package might be sufficient:

https://www.dropbox.com/s/qnmk283r54x4ucd/paramugsy_x86_ubuntu-12.04.tar.gz?dl=0

**Comment by orbitz** [comment]
Fixed in latest master! (At least on my system)

I would take the package I linked to above, and copy over your local builds to its directory structure.  This is a bit ugly unfortunately because you have to go into each subdirectory at the moment to find the built binary.  But I'll fix that soon.

Let me know if master doesn't work.

**Comment by orionzhou** [comment]
Thanks so much for the quick response - and magic fix! It now compiles and I'm doing test running. Everything looks good so far...
